### ISSUE TITLE
unable to determine transport target for "pino-mongodb"

### ISSUE THREAD

**Issue by toto1384** [pinojs/pino-mongodb#122]
The `pino-mongodb` library is installed

Here is the code

```
import pino from 'pino'
const transport = pino.transport({
	target: 'pino-mongodb',
	/* level: 'info', */
	options: {
		uri: `${(process.env.MONGODB_CONNECTION as string).split('27017')[0]}27017`,
		database: 'logs',
		collection: 'main',
		mongoOptions: {
			auth: {
				username: logins[0],
				password: logins[1]
			}
		}
	}
})

const logger = pino(transport)
```

Here is the error I am getting
```
error - Error: unable to determine transport target for "pino-mongodb"
    at fixTarget (/Users/alex/Mynextjob/CODE/complete/node_modules/.pnpm/pino@8.6.1/node_modules/pino/lib/transport.js:136:13)
    at Function.transport (/Users/alex/Mynextjob/CODE/complete/node_modules/.pnpm/pino@8.6.1/node_modules/pino/lib/transport.js:110:22)
    at eval (webpack-internal:///./utils/backend/backendMain.ts:116:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mcollina** [comment]
It seems you are running webpack without the additional config for transports.

https://github.com/pinojs/pino-webpack-plugin

**Comment by mahmoodhamdi** [comment]
As @mcollina mentioned, this is a bundler resolution issue. Pino transports are loaded by filename string (not by import), and bundlers like webpack don't know to include them in the bundle.

If you're using **Next.js** (which uses SWC/webpack internally), you have a few options:

1. **Use [pino-webpack-plugin](https://github.com/pinojs/pino-webpack-plugin)** — add it to your `next.config.js`:
   ```js
   const { PinoWebpackPlugin } = require("pino-webpack-plugin")
   
   module.exports = {
     webpack: (config) => {
       config.plugins.push(new PinoWebpackPlugin({ transports: ["pino-mongodb"] }))
       return config
     }
   }
   ```

2. **Mark pino-mongodb as external** in your bundler config so it's resolved at runtime from `node_modules`:
   ```js
   // next.config.js
   module.exports = {
     serverExternalPackages: ["pino", "pino-mongodb"]
   }
   ```

3. **Use the absolute path** as the transport target:
   ```js
   const transport = pino.transport({
     target: require.resolve("pino-mongodb")
   })
   ```

Option 2 is usually the simplest for Next.js apps.
