### ISSUE TITLE
no mongos proxy available

### ISSUE THREAD

**Issue by jsolivellase** [pinojs/pino-mongodb#7]
No problems connecting to db but when it is trying to write log to db throws the error:
`/usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/operations/mongo_client_ops.js:466
      throw err;
      ^

MongoError: no mongos proxy available
    at Timeout.<anonymous> (/usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:757:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

Any idea?

Thanks in advance!

**Comment by viktor-ku** [comment]
Hi @jsolivellase I have no idea. Maybe version of the client is outdated in this library? Have you tried forking it and bumping up the version?
