### ISSUE TITLE
Can't use the -o option

### ISSUE THREAD

**Issue by cm-trityum** [pinojs/pino-mongodb#76]
I'm try the get the inserted documents into stdout with command

`echo '{"foo": "bar"}' | pino-mongodb -o 'mongodb://localhost:27017/logs'`

but I get an error

```
/usr/local/lib/node_modules/pino-mongodb/lib/makeInsert.js:28
        process.stdout.write(JSON.stringify(result.ops[0]) + EOL)
                                                      ^

TypeError: Cannot read property '0' of undefined
    at callback (/usr/local/lib/node_modules/pino-mongodb/lib/makeInsert.js:28:55)
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/utils.js:532:9
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/operations/execute_operation.js:48:55
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/utils.js:532:9
    at completeEndSession (/usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/sessions.js:147:17)
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/sessions.js:157:13
    at Object.maybePromise (/usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/utils.js:518:5)
    at ClientSession.endSession (/usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/sessions.js:133:24)
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/operations/execute_operation.js:48:36
    at /usr/local/lib/node_modules/pino-mongodb/node_modules/mongodb/lib/operations/insert.js:53:13
```

Am I doing something wrong?

ps. the record is correctly saved in the database

**Comment by simoneb** [comment]
I suggest to close this as stale (no activity in 2+ months)
